# Generated by Django 4.2.24 on 2025-09-11 03:08

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("courses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_id",
                    models.CharField(max_length=50, unique=True, verbose_name="支付单号"),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("course_fee", "课程费用"),
                            ("registration_fee", "注册费"),
                            ("equipment_fee", "器材费"),
                            ("membership_fee", "会员费"),
                            ("penalty_fee", "违约金"),
                            ("other", "其他"),
                        ],
                        default="course_fee",
                        max_length=20,
                        verbose_name="支付类型",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="支付金额"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待支付"),
                            ("processing", "处理中"),
                            ("completed", "已完成"),
                            ("failed", "支付失败"),
                            ("cancelled", "已取消"),
                            ("refunded", "已退款"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="支付状态",
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="第三方交易号"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="支付描述"),
                ),
                (
                    "paid_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="支付时间"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "enrollment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="courses.courseenrollment",
                        verbose_name="关联报名",
                    ),
                ),
            ],
            options={
                "verbose_name": "支付记录",
                "verbose_name_plural": "支付记录",
                "db_table": "payments_payment",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="支付方式名称")),
                (
                    "method_type",
                    models.CharField(
                        choices=[
                            ("cash", "现金"),
                            ("wechat", "微信支付"),
                            ("alipay", "支付宝"),
                            ("bank_card", "银行卡"),
                            ("credit_card", "信用卡"),
                            ("other", "其他"),
                        ],
                        max_length=20,
                        verbose_name="支付类型",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否启用")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="描述"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "支付方式",
                "verbose_name_plural": "支付方式",
                "db_table": "payments_method",
            },
        ),
        migrations.CreateModel(
            name="UserAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="账户余额",
                    ),
                ),
                (
                    "frozen_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="冻结金额",
                    ),
                ),
                (
                    "total_paid",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="累计支付",
                    ),
                ),
                (
                    "total_refunded",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="累计退款",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="account",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户账户",
                "verbose_name_plural": "用户账户",
                "db_table": "payments_user_account",
            },
        ),
        migrations.CreateModel(
            name="Refund",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "refund_id",
                    models.CharField(max_length=50, unique=True, verbose_name="退款单号"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="退款金额"
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("course_cancelled", "课程取消"),
                            ("student_request", "学员申请"),
                            ("schedule_conflict", "时间冲突"),
                            ("quality_issue", "质量问题"),
                            ("other", "其他原因"),
                        ],
                        max_length=20,
                        verbose_name="退款原因",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("approved", "已批准"),
                            ("rejected", "已拒绝"),
                            ("processing", "处理中"),
                            ("completed", "已完成"),
                            ("failed", "退款失败"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="退款状态",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="退款说明"),
                ),
                (
                    "approved_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="审批时间"),
                ),
                (
                    "processed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="处理时间"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="申请时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={
                            "user_type__in": ["super_admin", "campus_admin"]
                        },
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_refunds",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="审批人",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refunds",
                        to="payments.payment",
                        verbose_name="原支付记录",
                    ),
                ),
            ],
            options={
                "verbose_name": "退款记录",
                "verbose_name_plural": "退款记录",
                "db_table": "payments_refund",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="payment",
            name="payment_method",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="payments.paymentmethod",
                verbose_name="支付方式",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="支付用户",
            ),
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(max_length=50, unique=True, verbose_name="发票号码"),
                ),
                (
                    "invoice_type",
                    models.CharField(
                        choices=[("personal", "个人"), ("company", "企业")],
                        max_length=20,
                        verbose_name="发票类型",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="发票抬头")),
                (
                    "tax_number",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="税号"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="发票金额"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待开具"),
                            ("issued", "已开具"),
                            ("sent", "已发送"),
                            ("cancelled", "已作废"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="发票状态",
                    ),
                ),
                (
                    "issued_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="开具时间"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="申请时间"),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="payments.payment",
                        verbose_name="关联支付",
                    ),
                ),
            ],
            options={
                "verbose_name": "发票",
                "verbose_name_plural": "发票",
                "db_table": "payments_invoice",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AccountTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("recharge", "充值"),
                            ("payment", "支付"),
                            ("refund", "退款"),
                            ("freeze", "冻结"),
                            ("unfreeze", "解冻"),
                            ("adjustment", "调整"),
                        ],
                        max_length=20,
                        verbose_name="交易类型",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="交易金额"
                    ),
                ),
                (
                    "balance_before",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="交易前余额"
                    ),
                ),
                (
                    "balance_after",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="交易后余额"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="交易描述"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="交易时间"),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="payments.useraccount",
                        verbose_name="账户",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="account_transactions",
                        to="payments.payment",
                        verbose_name="关联支付",
                    ),
                ),
            ],
            options={
                "verbose_name": "账户交易记录",
                "verbose_name_plural": "账户交易记录",
                "db_table": "payments_account_transaction",
                "ordering": ["-created_at"],
            },
        ),
    ]
