# Generated by Django 4.2.24 on 2025-09-26 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accounttransaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("recharge", "充值"),
                    ("payment", "支付"),
                    ("refund", "退款"),
                    ("freeze", "冻结"),
                    ("unfreeze", "解冻"),
                    ("adjustment", "调整"),
                    ("income", "收入"),
                ],
                max_length=20,
                verbose_name="交易类型",
            ),
        ),
    ]
