# Generated by Django 4.2.24 on 2025-09-11 04:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("campus", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField(verbose_name="开始时间")),
                ("end_time", models.DateTimeField(verbose_name="结束时间")),
                (
                    "duration_hours",
                    models.DecimalField(
                        decimal_places=1, max_digits=3, verbose_name="时长(小时)"
                    ),
                ),
                (
                    "total_fee",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="总费用"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待确认"),
                            ("confirmed", "已确认"),
                            ("completed", "已完成"),
                            ("cancelled", "已取消"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="预约状态",
                    ),
                ),
                (
                    "confirmed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="确认时间"),
                ),
                (
                    "cancelled_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="取消时间"),
                ),
                (
                    "cancel_reason",
                    models.TextField(blank=True, null=True, verbose_name="取消原因"),
                ),
                ("notes", models.TextField(blank=True, null=True, verbose_name="备注")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cancelled_bookings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="取消人",
                    ),
                ),
            ],
            options={
                "verbose_name": "预约",
                "verbose_name_plural": "预约",
                "db_table": "reservations_booking",
                "ordering": ["-start_time"],
            },
        ),
        migrations.CreateModel(
            name="Table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=10, verbose_name="球台编号")),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="球台名称"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "可用"),
                            ("occupied", "占用中"),
                            ("maintenance", "维护中"),
                            ("disabled", "停用"),
                        ],
                        default="available",
                        max_length=20,
                        verbose_name="球台状态",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="球台描述"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否启用")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "campus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tables",
                        to="campus.campus",
                        verbose_name="所属校区",
                    ),
                ),
            ],
            options={
                "verbose_name": "球台",
                "verbose_name_plural": "球台",
                "db_table": "reservations_table",
                "ordering": ["campus", "number"],
                "unique_together": {("campus", "number")},
            },
        ),
        migrations.CreateModel(
            name="CoachStudentRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待审核"),
                            ("approved", "已通过"),
                            ("rejected", "已拒绝"),
                            ("terminated", "已终止"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="关系状态",
                    ),
                ),
                (
                    "applied_by",
                    models.CharField(
                        choices=[("student", "学员申请"), ("coach", "教练申请")],
                        max_length=20,
                        verbose_name="申请方",
                    ),
                ),
                (
                    "applied_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="申请时间"
                    ),
                ),
                (
                    "processed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="处理时间"),
                ),
                (
                    "terminated_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="终止时间"),
                ),
                ("notes", models.TextField(blank=True, null=True, verbose_name="备注")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "coach",
                    models.ForeignKey(
                        limit_choices_to={"user_type": "coach"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_relations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="教练",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"user_type": "student"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coach_relations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="学员",
                    ),
                ),
            ],
            options={
                "verbose_name": "师生关系",
                "verbose_name_plural": "师生关系",
                "db_table": "reservations_coach_student_relation",
                "unique_together": {("coach", "student")},
            },
        ),
        migrations.CreateModel(
            name="BookingCancellation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.TextField(verbose_name="取消原因")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待确认"),
                            ("approved", "已同意"),
                            ("rejected", "已拒绝"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="申请状态",
                    ),
                ),
                (
                    "processed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="处理时间"),
                ),
                (
                    "response_message",
                    models.TextField(blank=True, null=True, verbose_name="回复消息"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="申请时间"),
                ),
                (
                    "booking",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cancellation",
                        to="reservations.booking",
                        verbose_name="预约",
                    ),
                ),
                (
                    "processed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="processed_cancellations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="处理人",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requested_cancellations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="申请人",
                    ),
                ),
            ],
            options={
                "verbose_name": "预约取消申请",
                "verbose_name_plural": "预约取消申请",
                "db_table": "reservations_booking_cancellation",
            },
        ),
        migrations.AddField(
            model_name="booking",
            name="relation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings",
                to="reservations.coachstudentrelation",
                verbose_name="师生关系",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="table",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings",
                to="reservations.table",
                verbose_name="球台",
            ),
        ),
    ]
