# Generated by Django 4.2.7 on 2025-09-15 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("reservations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CoachChangeRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        help_text="学员申请更换教练的原因", verbose_name="更换原因"
                    ),
                ),
                (
                    "request_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="申请时间"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待审核"),
                            ("approved", "已通过"),
                            ("rejected", "已拒绝"),
                            ("cancelled", "已取消"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="请求状态",
                    ),
                ),
                (
                    "current_coach_approval",
                    models.CharField(
                        choices=[
                            ("pending", "待审核"),
                            ("approved", "同意"),
                            ("rejected", "拒绝"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="当前教练审批状态",
                    ),
                ),
                (
                    "target_coach_approval",
                    models.CharField(
                        choices=[
                            ("pending", "待审核"),
                            ("approved", "同意"),
                            ("rejected", "拒绝"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="目标教练审批状态",
                    ),
                ),
                (
                    "campus_admin_approval",
                    models.CharField(
                        choices=[
                            ("pending", "待审核"),
                            ("approved", "同意"),
                            ("rejected", "拒绝"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="校区管理员审批状态",
                    ),
                ),
                (
                    "current_coach_approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="当前教练审批时间"
                    ),
                ),
                (
                    "target_coach_approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="目标教练审批时间"
                    ),
                ),
                (
                    "campus_admin_approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="校区管理员审批时间"
                    ),
                ),
                (
                    "current_coach_notes",
                    models.TextField(
                        blank=True, null=True, verbose_name="当前教练备注"
                    ),
                ),
                (
                    "target_coach_notes",
                    models.TextField(
                        blank=True, null=True, verbose_name="目标教练备注"
                    ),
                ),
                (
                    "campus_admin_notes",
                    models.TextField(
                        blank=True, null=True, verbose_name="校区管理员备注"
                    ),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="处理完成时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "campus_admin_approved_by",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"user_type": "campus_admin"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="campus_admin_approvals",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="校区管理员审批人",
                    ),
                ),
                (
                    "current_coach",
                    models.ForeignKey(
                        limit_choices_to={"user_type": "coach"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="current_coach_change_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="当前教练",
                    ),
                ),
                (
                    "current_coach_approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="current_coach_approvals",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="当前教练审批人",
                    ),
                ),
                (
                    "processed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="processed_coach_changes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="处理人",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"user_type": "student"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coach_change_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="学员",
                    ),
                ),
                (
                    "target_coach",
                    models.ForeignKey(
                        limit_choices_to={"user_type": "coach"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="target_coach_change_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="目标教练",
                    ),
                ),
                (
                    "target_coach_approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="target_coach_approvals",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="目标教练审批人",
                    ),
                ),
            ],
            options={
                "verbose_name": "教练员更换请求",
                "verbose_name_plural": "教练员更换请求",
                "db_table": "reservations_coach_change_request",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="coachchangerequest",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "pending")),
                fields=("student",),
                name="unique_pending_coach_change_per_student",
            ),
        ),
    ]
