# Generated by Django 4.2.24 on 2025-09-26 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0003_alter_booking_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("unpaid", "未支付"),
                    ("partial", "部分支付"),
                    ("paid", "已支付"),
                    ("refunded", "已退款"),
                ],
                default="unpaid",
                max_length=20,
                verbose_name="支付状态",
            ),
        ),
    ]
