# Generated by Django 4.2.24 on 2025-09-12 08:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coach",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "coach_level",
                    models.CharField(
                        choices=[
                            ("junior", "初级教练员"),
                            ("intermediate", "中级教练员"),
                            ("senior", "高级教练员"),
                        ],
                        default="junior",
                        max_length=20,
                        verbose_name="教练级别",
                    ),
                ),
                (
                    "hourly_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=80.0,
                        max_digits=8,
                        verbose_name="时薪（元/小时）",
                    ),
                ),
                (
                    "achievements",
                    models.TextField(blank=True, null=True, verbose_name="比赛成绩描述"),
                ),
                (
                    "max_students",
                    models.PositiveIntegerField(default=20, verbose_name="最大学员数"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待审核"),
                            ("approved", "已通过"),
                            ("rejected", "已拒绝"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="审核状态",
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="审核时间"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"user_type": "campus_admin"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_coaches",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="审核人",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        limit_choices_to={"user_type": "coach"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coach_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "教练员",
                "verbose_name_plural": "教练员",
                "db_table": "accounts_coach",
                "ordering": ["-created_at"],
            },
        ),
    ]
