# Generated by Django 4.2.24 on 2025-09-12 10:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_coach"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                max_length=500,
                null=True,
                upload_to="avatars/",
                verbose_name="头像",
            ),
        ),
    ]
