# Generated by Django 4.2.24 on 2025-09-11 03:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Campus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="校区名称"),
                ),
                (
                    "code",
                    models.CharField(max_length=20, unique=True, verbose_name="校区编码"),
                ),
                ("address", models.TextField(verbose_name="校区地址")),
                ("phone", models.CharField(max_length=20, verbose_name="联系电话")),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="邮箱"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="校区描述"),
                ),
                (
                    "facilities",
                    models.TextField(blank=True, null=True, verbose_name="设施介绍"),
                ),
                (
                    "operating_hours",
                    models.CharField(
                        default="09:00-21:00", max_length=100, verbose_name="营业时间"
                    ),
                ),
                (
                    "capacity",
                    models.PositiveIntegerField(default=100, verbose_name="容纳人数"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否启用")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"user_type": "campus_admin"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_campus",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="校区管理员",
                    ),
                ),
            ],
            options={
                "verbose_name": "校区",
                "verbose_name_plural": "校区",
                "db_table": "campus_campus",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CampusStudent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enrollment_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="入学时间"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否活跃")),
                ("notes", models.TextField(blank=True, null=True, verbose_name="备注")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "campus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="students",
                        to="campus.campus",
                        verbose_name="校区",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"user_type": "student"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campus_memberships",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="学员",
                    ),
                ),
            ],
            options={
                "verbose_name": "校区学员",
                "verbose_name_plural": "校区学员",
                "db_table": "campus_student",
                "unique_together": {("campus", "student")},
            },
        ),
        migrations.CreateModel(
            name="CampusCoach",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hire_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="入职时间"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否在职")),
                (
                    "specialties",
                    models.TextField(blank=True, null=True, verbose_name="专业特长"),
                ),
                (
                    "max_students",
                    models.PositiveIntegerField(default=20, verbose_name="最大学员数"),
                ),
                (
                    "hourly_rate",
                    models.DecimalField(
                        decimal_places=2, default=0.0, max_digits=8, verbose_name="时薪"
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True, verbose_name="备注")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "campus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coaches",
                        to="campus.campus",
                        verbose_name="校区",
                    ),
                ),
                (
                    "coach",
                    models.ForeignKey(
                        limit_choices_to={"user_type": "coach"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campus_assignments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="教练",
                    ),
                ),
            ],
            options={
                "verbose_name": "校区教练",
                "verbose_name_plural": "校区教练",
                "db_table": "campus_coach",
                "unique_together": {("campus", "coach")},
            },
        ),
        migrations.CreateModel(
            name="CampusArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="分区名称")),
                (
                    "area_type",
                    models.CharField(
                        choices=[
                            ("training", "训练区"),
                            ("rest", "休息区"),
                            ("equipment", "器材区"),
                            ("office", "办公区"),
                            ("reception", "接待区"),
                            ("other", "其他"),
                        ],
                        max_length=20,
                        verbose_name="分区类型",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="分区描述"),
                ),
                (
                    "capacity",
                    models.PositiveIntegerField(default=10, verbose_name="容纳人数"),
                ),
                (
                    "equipment_list",
                    models.TextField(blank=True, null=True, verbose_name="设备清单"),
                ),
                (
                    "is_available",
                    models.BooleanField(default=True, verbose_name="是否可用"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "campus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="areas",
                        to="campus.campus",
                        verbose_name="所属校区",
                    ),
                ),
            ],
            options={
                "verbose_name": "校区分区",
                "verbose_name_plural": "校区分区",
                "db_table": "campus_area",
                "unique_together": {("campus", "name")},
            },
        ),
    ]
