# Generated by Django 4.2.24 on 2025-09-11 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("campus", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="campus",
            name="campus_type",
            field=models.CharField(
                choices=[("center", "中心校区"), ("branch", "分校区")],
                default="branch",
                max_length=10,
                verbose_name="校区类型",
            ),
        ),
        migrations.AddField(
            model_name="campus",
            name="contact_person",
            field=models.CharField(default="待填写", max_length=50, verbose_name="联系人"),
        ),
        migrations.AddField(
            model_name="campus",
            name="parent_campus",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"campus_type": "center"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="branch_campuses",
                to="campus.campus",
                verbose_name="上级校区",
            ),
        ),
        migrations.AlterField(
            model_name="campus",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"user_type__in": ["campus_admin", "super_admin"]},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managed_campus",
                to=settings.AUTH_USER_MODEL,
                verbose_name="校区管理员",
            ),
        ),
    ]
