# Generated by Django 4.2.24 on 2025-09-11 10:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("campus", "0002_campus_campus_type_campus_contact_person_and_more"),
    ]

    operations = []
