# Generated by Django 4.2.24 on 2025-09-11 03:08

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("campus", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="课程名称")),
                ("description", models.TextField(verbose_name="课程描述")),
                (
                    "course_type",
                    models.CharField(
                        choices=[
                            ("beginner", "初级课程"),
                            ("intermediate", "中级课程"),
                            ("advanced", "高级课程"),
                            ("private", "私教课程"),
                            ("group", "团体课程"),
                        ],
                        max_length=20,
                        verbose_name="课程类型",
                    ),
                ),
                (
                    "max_students",
                    models.PositiveIntegerField(default=10, verbose_name="最大学员数"),
                ),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(default=60, verbose_name="课程时长(分钟)"),
                ),
                (
                    "price_per_session",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=8,
                        verbose_name="单次课程价格",
                    ),
                ),
                (
                    "total_sessions",
                    models.PositiveIntegerField(default=1, verbose_name="总课时数"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("published", "已发布"),
                            ("suspended", "暂停"),
                            ("cancelled", "已取消"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="课程状态",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="开始日期")),
                ("end_date", models.DateField(verbose_name="结束日期")),
                (
                    "requirements",
                    models.TextField(blank=True, null=True, verbose_name="课程要求"),
                ),
                (
                    "equipment_needed",
                    models.TextField(blank=True, null=True, verbose_name="所需器材"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "area",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="courses",
                        to="campus.campusarea",
                        verbose_name="上课区域",
                    ),
                ),
                (
                    "campus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="courses",
                        to="campus.campus",
                        verbose_name="所属校区",
                    ),
                ),
                (
                    "coach",
                    models.ForeignKey(
                        limit_choices_to={"user_type": "coach"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teaching_courses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="授课教练",
                    ),
                ),
            ],
            options={
                "verbose_name": "课程",
                "verbose_name_plural": "课程",
                "db_table": "courses_course",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CourseSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_number", models.PositiveIntegerField(verbose_name="课时编号")),
                ("scheduled_date", models.DateField(verbose_name="计划日期")),
                ("scheduled_time", models.TimeField(verbose_name="计划时间")),
                (
                    "actual_start_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="实际开始时间"),
                ),
                (
                    "actual_end_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="实际结束时间"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "已安排"),
                            ("in_progress", "进行中"),
                            ("completed", "已完成"),
                            ("cancelled", "已取消"),
                            ("postponed", "已延期"),
                        ],
                        default="scheduled",
                        max_length=20,
                        verbose_name="课时状态",
                    ),
                ),
                (
                    "content",
                    models.TextField(blank=True, null=True, verbose_name="课程内容"),
                ),
                (
                    "homework",
                    models.TextField(blank=True, null=True, verbose_name="课后作业"),
                ),
                ("notes", models.TextField(blank=True, null=True, verbose_name="备注")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="courses.course",
                        verbose_name="课程",
                    ),
                ),
            ],
            options={
                "verbose_name": "课程课时",
                "verbose_name_plural": "课程课时",
                "db_table": "courses_session",
                "ordering": ["course", "session_number"],
                "unique_together": {("course", "session_number")},
            },
        ),
        migrations.CreateModel(
            name="CourseSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weekday",
                    models.IntegerField(
                        choices=[
                            (0, "周一"),
                            (1, "周二"),
                            (2, "周三"),
                            (3, "周四"),
                            (4, "周五"),
                            (5, "周六"),
                            (6, "周日"),
                        ],
                        verbose_name="星期",
                    ),
                ),
                ("start_time", models.TimeField(verbose_name="开始时间")),
                ("end_time", models.TimeField(verbose_name="结束时间")),
                ("is_active", models.BooleanField(default=True, verbose_name="是否启用")),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="courses.course",
                        verbose_name="课程",
                    ),
                ),
            ],
            options={
                "verbose_name": "课程时间表",
                "verbose_name_plural": "课程时间表",
                "db_table": "courses_schedule",
                "unique_together": {("course", "weekday", "start_time")},
            },
        ),
        migrations.CreateModel(
            name="CourseEvaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="评分(1-5)",
                    ),
                ),
                (
                    "comment",
                    models.TextField(blank=True, null=True, verbose_name="评价内容"),
                ),
                (
                    "coach_rating",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="教练评分(1-5)",
                    ),
                ),
                (
                    "facility_rating",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="设施评分(1-5)",
                    ),
                ),
                (
                    "is_anonymous",
                    models.BooleanField(default=False, verbose_name="是否匿名"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="评价时间"),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluations",
                        to="courses.course",
                        verbose_name="课程",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"user_type": "student"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_evaluations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="学员",
                    ),
                ),
            ],
            options={
                "verbose_name": "课程评价",
                "verbose_name_plural": "课程评价",
                "db_table": "courses_evaluation",
                "unique_together": {("course", "student")},
            },
        ),
        migrations.CreateModel(
            name="CourseEnrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enrollment_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="报名时间"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待确认"),
                            ("confirmed", "已确认"),
                            ("cancelled", "已取消"),
                            ("completed", "已完成"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="报名状态",
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("unpaid", "未支付"),
                            ("partial", "部分支付"),
                            ("paid", "已支付"),
                            ("refunded", "已退款"),
                        ],
                        default="unpaid",
                        max_length=20,
                        verbose_name="支付状态",
                    ),
                ),
                (
                    "paid_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=8,
                        verbose_name="已支付金额",
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True, verbose_name="备注")),
                ("is_active", models.BooleanField(default=True, verbose_name="是否活跃")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="courses.course",
                        verbose_name="课程",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"user_type": "student"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_enrollments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="学员",
                    ),
                ),
            ],
            options={
                "verbose_name": "课程报名",
                "verbose_name_plural": "课程报名",
                "db_table": "courses_enrollment",
                "unique_together": {("course", "student")},
            },
        ),
        migrations.CreateModel(
            name="CourseAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("present", "出席"),
                            ("absent", "缺席"),
                            ("late", "迟到"),
                            ("leave_early", "早退"),
                            ("excused", "请假"),
                        ],
                        default="present",
                        max_length=20,
                        verbose_name="考勤状态",
                    ),
                ),
                (
                    "check_in_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="签到时间"),
                ),
                (
                    "check_out_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="签退时间"),
                ),
                ("notes", models.TextField(blank=True, null=True, verbose_name="备注")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendances",
                        to="courses.coursesession",
                        verbose_name="课时",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"user_type": "student"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_attendances",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="学员",
                    ),
                ),
            ],
            options={
                "verbose_name": "课程考勤",
                "verbose_name_plural": "课程考勤",
                "db_table": "courses_attendance",
                "unique_together": {("session", "student")},
            },
        ),
    ]
