# Generated by Django 4.2.24 on 2025-09-12 06:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("competitions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="competitionregistration",
            name="participant",
            field=models.ForeignKey(
                limit_choices_to={"user_type": "student"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="competition_registrations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="参赛者",
            ),
        ),
    ]
