# Generated by Django 4.2.7 on 2025-09-22 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("competitions", "0002_alter_competitionregistration_participant"),
    ]

    operations = [
        migrations.AddField(
            model_name="competition",
            name="competition_type",
            field=models.CharField(
                choices=[
                    ("monthly", "月赛"),
                    ("single", "单打"),
                    ("double", "双打"),
                    ("team", "团体赛"),
                ],
                default="monthly",
                max_length=20,
                verbose_name="比赛类型",
            ),
        ),
        migrations.AddField(
            model_name="competition",
            name="name",
            field=models.CharField(
                default="默认比赛", max_length=200, verbose_name="比赛名称"
            ),
        ),
    ]
