# Generated by Django 4.2.7 on 2025-09-22 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("campus", "0003_auto_20250911_1813"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("create", "创建"),
                            ("update", "更新"),
                            ("delete", "删除"),
                            ("login", "登录"),
                            ("logout", "登出"),
                            ("approve", "审核"),
                            ("reject", "拒绝"),
                            ("cancel", "取消"),
                            ("confirm", "确认"),
                            ("payment", "支付"),
                            ("refund", "退款"),
                            ("register", "注册"),
                            ("other", "其他"),
                        ],
                        max_length=20,
                        verbose_name="操作类型",
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("user", "用户"),
                            ("campus", "校区"),
                            ("student", "学员"),
                            ("coach", "教练"),
                            ("booking", "预约"),
                            ("course", "课程"),
                            ("payment", "支付"),
                            ("competition", "比赛"),
                            ("notification", "通知"),
                            ("system", "系统"),
                            ("other", "其他"),
                        ],
                        max_length=20,
                        verbose_name="资源类型",
                    ),
                ),
                (
                    "resource_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="资源ID"
                    ),
                ),
                (
                    "resource_name",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="资源名称"
                    ),
                ),
                ("description", models.TextField(verbose_name="操作描述")),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP地址"
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, null=True, verbose_name="用户代理"),
                ),
                (
                    "extra_data",
                    models.JSONField(blank=True, default=dict, verbose_name="额外数据"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="操作时间"
                    ),
                ),
                (
                    "campus",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="operation_logs",
                        to="campus.campus",
                        verbose_name="所属校区",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="operation_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="操作用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "系统日志",
                "verbose_name_plural": "系统日志",
                "db_table": "logs_system_log",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"],
                        name="logs_system_user_id_85f0a6_idx",
                    ),
                    models.Index(
                        fields=["action_type", "created_at"],
                        name="logs_system_action__ccff14_idx",
                    ),
                    models.Index(
                        fields=["resource_type", "created_at"],
                        name="logs_system_resourc_628b97_idx",
                    ),
                    models.Index(
                        fields=["campus", "created_at"],
                        name="logs_system_campus__b981c5_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="LoginLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "login_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="登录时间"
                    ),
                ),
                (
                    "logout_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="登出时间"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP地址"
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, null=True, verbose_name="用户代理"),
                ),
                (
                    "session_key",
                    models.CharField(
                        blank=True, max_length=40, null=True, verbose_name="会话密钥"
                    ),
                ),
                (
                    "is_successful",
                    models.BooleanField(default=True, verbose_name="是否成功"),
                ),
                (
                    "failure_reason",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="失败原因"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="login_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "登录日志",
                "verbose_name_plural": "登录日志",
                "db_table": "logs_login_log",
                "ordering": ["-login_time"],
                "indexes": [
                    models.Index(
                        fields=["user", "login_time"],
                        name="logs_login__user_id_261ed6_idx",
                    ),
                    models.Index(
                        fields=["ip_address", "login_time"],
                        name="logs_login__ip_addr_2d5f56_idx",
                    ),
                ],
            },
        ),
    ]
